create table user (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	first VARCHAR(50),
	last VARCHAR(50),
	gender VARCHAR(50),
	avatar VARCHAR(250),
	username VARCHAR(50),
	password VARCHAR(50)
);
insert into user (first, last, gender, avatar, username, password) values ('Meier', 'Garci', 'Male', 'https://robohash.org/impeditsequiducimus.png?size=200x200&set=set1', 'mgarci0', 'uYyf8ZFJuV');
insert into user (first, last, gender, avatar, username, password) values ('Bruno', 'Maffulli', 'Male', 'https://robohash.org/rationedoloribusest.png?size=200x200&set=set1', 'bmaffulli1', 'dblUxYreU');
insert into user (first, last, gender, avatar, username, password) values ('Salome', 'Burnel', 'Female', 'https://robohash.org/impeditsedfugiat.png?size=200x200&set=set1', 'sburnel2', 'uZi7omTd');
insert into user (first, last, gender, avatar, username, password) values ('Sabina', 'Berthomieu', 'Female', 'https://robohash.org/animiquiaut.png?size=200x200&set=set1', 'sberthomieu3', 'I3Y2QKI');
insert into user (first, last, gender, avatar, username, password) values ('Niven', 'Haskur', 'Male', 'https://robohash.org/facereutet.png?size=200x200&set=set1', 'nhaskur4', 'NQBkTR6vVMV');
insert into user (first, last, gender, avatar, username, password) values ('Sally', 'Ewence', 'Female', 'https://robohash.org/suntculpasaepe.png?size=200x200&set=set1', 'sewence5', 'Zko1a66jZV3o');
insert into user (first, last, gender, avatar, username, password) values ('Der', 'Basile', 'Male', 'https://robohash.org/voluptasducimuslabore.png?size=200x200&set=set1', 'dbasile6', 'HPgsACyGmj');
insert into user (first, last, gender, avatar, username, password) values ('Ryley', 'Matias', 'Male', 'https://robohash.org/veritatisquiaconsequatur.png?size=200x200&set=set1', 'rmatias7', 'RQscFfYa48Rt');
insert into user (first, last, gender, avatar, username, password) values ('Dena', 'Kempson', 'Female', 'https://robohash.org/reprehenderitnisieos.png?size=200x200&set=set1', 'dkempson8', 'sKBIwkDj6C');
insert into user (first, last, gender, avatar, username, password) values ('Phillipp', 'Dack', 'Male', 'https://robohash.org/oditestreprehenderit.png?size=200x200&set=set1', 'pdack9', '4BITRZ4OrYKO');
insert into user (first, last, gender, avatar, username, password) values ('Heidie', 'Thomel', 'Female', 'https://robohash.org/omniseosnostrum.png?size=200x200&set=set1', 'hthomela', 'P9219ScB');
insert into user (first, last, gender, avatar, username, password) values ('Vern', 'Krop', 'Male', 'https://robohash.org/etvoluptatibusquibusdam.png?size=200x200&set=set1', 'vkropb', 'iotmXjNBw2iM');
insert into user (first, last, gender, avatar, username, password) values ('Malorie', 'Poli', 'Female', 'https://robohash.org/cumcumqueomnis.png?size=200x200&set=set1', 'mpolic', 'tXoKXnxwbB');
insert into user (first, last, gender, avatar, username, password) values ('Yasmin', 'Mival', 'Female', 'https://robohash.org/ametoditea.png?size=200x200&set=set1', 'ymivald', 'Sr9S1VoKEZ');
insert into user (first, last, gender, avatar, username, password) values ('Nada', 'Kinnard', 'Female', 'https://robohash.org/velimpeditomnis.png?size=200x200&set=set1', 'nkinnarde', 'fES3vDl');
insert into user (first, last, gender, avatar, username, password) values ('Garwin', 'Jakoviljevic', 'Male', 'https://robohash.org/nulladictaarchitecto.png?size=200x200&set=set1', 'gjakoviljevicf', 'llF0DRw7Ra');
insert into user (first, last, gender, avatar, username, password) values ('Shayne', 'Puddephatt', 'Female', 'https://robohash.org/adomnismolestiae.png?size=200x200&set=set1', 'spuddephattg', 'vs98waeWUu0');
insert into user (first, last, gender, avatar, username, password) values ('Karon', 'Jarman', 'Female', 'https://robohash.org/molestiaeestunde.png?size=200x200&set=set1', 'kjarmanh', 'B4So5mQA');
insert into user (first, last, gender, avatar, username, password) values ('Augie', 'MacConnell', 'Male', 'https://robohash.org/eamodiperspiciatis.png?size=200x200&set=set1', 'amacconnelli', 'ndXlvoq5C3');
insert into user (first, last, gender, avatar, username, password) values ('Emyle', 'Older', 'Female', 'https://robohash.org/nullaestsapiente.png?size=200x200&set=set1', 'eolderj', 'XyzbJ3');
insert into user (first, last, gender, avatar, username, password) values ('Mackenzie', 'Rowcastle', 'Male', 'https://robohash.org/consequaturestiste.png?size=200x200&set=set1', 'mrowcastlek', 'JTStimbBdeJ7');
insert into user (first, last, gender, avatar, username, password) values ('Adrian', 'Ghirigori', 'Male', 'https://robohash.org/laborumtotamvoluptatem.png?size=200x200&set=set1', 'aghirigoril', '8UadVbPdggw');
insert into user (first, last, gender, avatar, username, password) values ('Frances', 'Solesbury', 'Female', 'https://robohash.org/enimsuscipitrem.png?size=200x200&set=set1', 'fsolesburym', 'YjaUpRy');
insert into user (first, last, gender, avatar, username, password) values ('Ag', 'Darey', 'Female', 'https://robohash.org/minimaiureconsequatur.png?size=200x200&set=set1', 'adareyn', 'uhe0f0l');
insert into user (first, last, gender, avatar, username, password) values ('Leese', 'Grebner', 'Female', 'https://robohash.org/etsitquibusdam.png?size=200x200&set=set1', 'lgrebnero', 'GpdYrhCh');
insert into user (first, last, gender, avatar, username, password) values ('Charmion', 'Yates', 'Female', 'https://robohash.org/utplaceatexpedita.png?size=200x200&set=set1', 'cyatesp', 'nwjIKzy');
insert into user (first, last, gender, avatar, username, password) values ('Mohandis', 'Cossar', 'Male', 'https://robohash.org/doloremnemocorrupti.png?size=200x200&set=set1', 'mcossarq', 'AHLwJH');
insert into user (first, last, gender, avatar, username, password) values ('Scott', 'Glasscock', 'Male', 'https://robohash.org/atsuntet.png?size=200x200&set=set1', 'sglasscockr', 'URMhyS5czT1');
insert into user (first, last, gender, avatar, username, password) values ('Kristofor', 'De Antoni', 'Male', 'https://robohash.org/repellenduseaqueculpa.png?size=200x200&set=set1', 'kdeantonis', 'BwguId');
insert into user (first, last, gender, avatar, username, password) values ('Rayna', 'Roscamps', 'Female', 'https://robohash.org/delenitivoluptatemamet.png?size=200x200&set=set1', 'rroscampst', 'FZVPcadn');
insert into user (first, last, gender, avatar, username, password) values ('Robbyn', 'Nisard', 'Female', 'https://robohash.org/delenitinihileum.png?size=200x200&set=set1', 'rnisardu', 'JOijkyU');
insert into user (first, last, gender, avatar, username, password) values ('Sonny', 'O''Hanley', 'Male', 'https://robohash.org/ipsamcumrepellat.png?size=200x200&set=set1', 'sohanleyv', 'WF4erSXi6m');
insert into user (first, last, gender, avatar, username, password) values ('Francklin', 'Dummigan', 'Male', 'https://robohash.org/utvoluptatesinventore.png?size=200x200&set=set1', 'fdummiganw', 'Dq0l2HIS55Vc');
insert into user (first, last, gender, avatar, username, password) values ('Bendix', 'Brombell', 'Male', 'https://robohash.org/doloribusrepellatnemo.png?size=200x200&set=set1', 'bbrombellx', 'rJVx7u');
insert into user (first, last, gender, avatar, username, password) values ('Vonny', 'Gammel', 'Female', 'https://robohash.org/officiisestnon.png?size=200x200&set=set1', 'vgammely', 'ygWjas');
insert into user (first, last, gender, avatar, username, password) values ('Flint', 'Gorse', 'Male', 'https://robohash.org/autemsequiquo.png?size=200x200&set=set1', 'fgorsez', 'jXGXs6l');
insert into user (first, last, gender, avatar, username, password) values ('Iorgos', 'Cappel', 'Male', 'https://robohash.org/assumendadolorumin.png?size=200x200&set=set1', 'icappel10', 'LywDb2lTNfk');
insert into user (first, last, gender, avatar, username, password) values ('Bernardina', 'Beever', 'Female', 'https://robohash.org/velitfugiatet.png?size=200x200&set=set1', 'bbeever11', '16mv5r2');
insert into user (first, last, gender, avatar, username, password) values ('Anselma', 'Stawell', 'Female', 'https://robohash.org/ipsumquisquamad.png?size=200x200&set=set1', 'astawell12', 'qeqZZ68Xn1');
insert into user (first, last, gender, avatar, username, password) values ('Shel', 'Hucquart', 'Female', 'https://robohash.org/voluptatemaamet.png?size=200x200&set=set1', 'shucquart13', 'qauMHVur');
insert into user (first, last, gender, avatar, username, password) values ('Tamera', 'Willmore', 'Female', 'https://robohash.org/fugitautaut.png?size=200x200&set=set1', 'twillmore14', '8TUux5xlkL1x');
insert into user (first, last, gender, avatar, username, password) values ('Wolfy', 'Swindles', 'Male', 'https://robohash.org/nihilsitut.png?size=200x200&set=set1', 'wswindles15', 'P7EykoP');
insert into user (first, last, gender, avatar, username, password) values ('Antonino', 'Ranson', 'Male', 'https://robohash.org/architectoipsumquo.png?size=200x200&set=set1', 'aranson16', 'UdbcmLTQK5Tp');
insert into user (first, last, gender, avatar, username, password) values ('Peyter', 'Crosham', 'Male', 'https://robohash.org/abvoluptasut.png?size=200x200&set=set1', 'pcrosham17', '8pqDwYzS');
insert into user (first, last, gender, avatar, username, password) values ('Anatola', 'O''Hara', 'Female', 'https://robohash.org/maximeearumperspiciatis.png?size=200x200&set=set1', 'aohara18', 'SG16QB');
insert into user (first, last, gender, avatar, username, password) values ('Thedrick', 'Cursey', 'Male', 'https://robohash.org/estatqueenim.png?size=200x200&set=set1', 'tcursey19', 'dUYQmMw4');
insert into user (first, last, gender, avatar, username, password) values ('Orly', 'Totman', 'Female', 'https://robohash.org/nullaperspiciatisconsectetur.png?size=200x200&set=set1', 'ototman1a', 'fl8QHh');
insert into user (first, last, gender, avatar, username, password) values ('Corrianne', 'Smolan', 'Female', 'https://robohash.org/abdoloremquequisquam.png?size=200x200&set=set1', 'csmolan1b', 'SmIVTZbSUJ');
insert into user (first, last, gender, avatar, username, password) values ('Estrella', 'Wyon', 'Female', 'https://robohash.org/evenietsintadipisci.png?size=200x200&set=set1', 'ewyon1c', 'yRTLVGcQ7JRc');
insert into user (first, last, gender, avatar, username, password) values ('Ulberto', 'Swannie', 'Male', 'https://robohash.org/doloremqueducimusmodi.png?size=200x200&set=set1', 'uswannie1d', '5f4E7CRp');
insert into user (first, last, gender, avatar, username, password) values ('Garold', 'Buttfield', 'Male', 'https://robohash.org/sitquiaatque.png?size=200x200&set=set1', 'gbuttfield1e', 'jC9TUVpDd2');
insert into user (first, last, gender, avatar, username, password) values ('Raoul', 'Edgecombe', 'Male', 'https://robohash.org/enimsitdistinctio.png?size=200x200&set=set1', 'redgecombe1f', 'TJlxsj');
insert into user (first, last, gender, avatar, username, password) values ('Hillyer', 'Yakovlev', 'Male', 'https://robohash.org/quiaminusaut.png?size=200x200&set=set1', 'hyakovlev1g', 'dlJsJuD');
insert into user (first, last, gender, avatar, username, password) values ('Chelsy', 'Chawkley', 'Female', 'https://robohash.org/suntperspiciatisvoluptatem.png?size=200x200&set=set1', 'cchawkley1h', 'KUVYBk');
insert into user (first, last, gender, avatar, username, password) values ('Darbie', 'Chadbourne', 'Female', 'https://robohash.org/iurenonqui.png?size=200x200&set=set1', 'dchadbourne1i', 'i6cxrus');
insert into user (first, last, gender, avatar, username, password) values ('Hirsch', 'Taphouse', 'Male', 'https://robohash.org/rationesedvoluptatem.png?size=200x200&set=set1', 'htaphouse1j', 'HwEfuB3LQ');
insert into user (first, last, gender, avatar, username, password) values ('Conant', 'Johanchon', 'Male', 'https://robohash.org/ullamomnisperferendis.png?size=200x200&set=set1', 'cjohanchon1k', 'xZeXdB');
insert into user (first, last, gender, avatar, username, password) values ('Leland', 'De Blasiis', 'Male', 'https://robohash.org/utdictaconsectetur.png?size=200x200&set=set1', 'ldeblasiis1l', 'JztHgUWhPn3v');
insert into user (first, last, gender, avatar, username, password) values ('Zuzana', 'Doogood', 'Female', 'https://robohash.org/explicaboetsoluta.png?size=200x200&set=set1', 'zdoogood1m', 'p16rNUzB3');
insert into user (first, last, gender, avatar, username, password) values ('Martie', 'Spry', 'Male', 'https://robohash.org/corruptiametadipisci.png?size=200x200&set=set1', 'mspry1n', 'l6hv5MU4flw');
insert into user (first, last, gender, avatar, username, password) values ('Boothe', 'Gooder', 'Male', 'https://robohash.org/animiistetempora.png?size=200x200&set=set1', 'bgooder1o', 'WhegMZ2p');
insert into user (first, last, gender, avatar, username, password) values ('Patricio', 'Killshaw', 'Male', 'https://robohash.org/exinciduntquia.png?size=200x200&set=set1', 'pkillshaw1p', 'It76P7JP');
insert into user (first, last, gender, avatar, username, password) values ('Izzy', 'McGriffin', 'Male', 'https://robohash.org/occaecatiabitaque.png?size=200x200&set=set1', 'imcgriffin1q', 'MVZtNDbfb');
insert into user (first, last, gender, avatar, username, password) values ('Kathie', 'Kringe', 'Female', 'https://robohash.org/facerevoluptatemipsa.png?size=200x200&set=set1', 'kkringe1r', 'zBQ8B8LF');
insert into user (first, last, gender, avatar, username, password) values ('Terencio', 'Risely', 'Male', 'https://robohash.org/utatqueofficia.png?size=200x200&set=set1', 'trisely1s', 'vDxdsQZ2Qh97');
insert into user (first, last, gender, avatar, username, password) values ('Gusty', 'Prigmore', 'Female', 'https://robohash.org/etutrepellendus.png?size=200x200&set=set1', 'gprigmore1t', 'UtX9w9');
insert into user (first, last, gender, avatar, username, password) values ('Sayres', 'Brockett', 'Male', 'https://robohash.org/etametinventore.png?size=200x200&set=set1', 'sbrockett1u', '8vAClSdyuC');
insert into user (first, last, gender, avatar, username, password) values ('Simone', 'Carlet', 'Female', 'https://robohash.org/possimusodiorerum.png?size=200x200&set=set1', 'scarlet1v', 'cn2CmFU0Vz');
insert into user (first, last, gender, avatar, username, password) values ('Colleen', 'Partridge', 'Female', 'https://robohash.org/molestiasexplicaboerror.png?size=200x200&set=set1', 'cpartridge1w', 'dMnnZ4XKAsiG');
insert into user (first, last, gender, avatar, username, password) values ('Delora', 'Devons', 'Female', 'https://robohash.org/mollitianostrumest.png?size=200x200&set=set1', 'ddevons1x', '42J7pLXy');
insert into user (first, last, gender, avatar, username, password) values ('Milli', 'Gowdy', 'Female', 'https://robohash.org/maximeutdebitis.png?size=200x200&set=set1', 'mgowdy1y', 'JdyBTmWMYh6R');
insert into user (first, last, gender, avatar, username, password) values ('Nolan', 'Brecken', 'Male', 'https://robohash.org/utvoluptaserror.png?size=200x200&set=set1', 'nbrecken1z', 'tnfcgTi');
insert into user (first, last, gender, avatar, username, password) values ('Maxy', 'Gilmore', 'Female', 'https://robohash.org/oditnonarchitecto.png?size=200x200&set=set1', 'mgilmore20', 'b6TY1T3umttQ');
insert into user (first, last, gender, avatar, username, password) values ('Ingemar', 'Brimm', 'Male', 'https://robohash.org/quinisimolestiae.png?size=200x200&set=set1', 'ibrimm21', 'JBwt3ER');
insert into user (first, last, gender, avatar, username, password) values ('Chrisy', 'Maslin', 'Male', 'https://robohash.org/nemoquianesciunt.png?size=200x200&set=set1', 'cmaslin22', 'V334aAN');
insert into user (first, last, gender, avatar, username, password) values ('Michele', 'Donaghy', 'Male', 'https://robohash.org/maioresautesse.png?size=200x200&set=set1', 'mdonaghy23', 'ySxvIY6ch0');
insert into user (first, last, gender, avatar, username, password) values ('Sigfrid', 'Gate', 'Male', 'https://robohash.org/dolorvoluptatemid.png?size=200x200&set=set1', 'sgate24', 'jQtus7AMaw');
insert into user (first, last, gender, avatar, username, password) values ('Rory', 'Pidgeon', 'Male', 'https://robohash.org/autquiaquis.png?size=200x200&set=set1', 'rpidgeon25', 'QQGJkp1');
insert into user (first, last, gender, avatar, username, password) values ('Andie', 'Harrild', 'Male', 'https://robohash.org/autetmaiores.png?size=200x200&set=set1', 'aharrild26', 'fwEQq7R833');
insert into user (first, last, gender, avatar, username, password) values ('Caril', 'MacLise', 'Female', 'https://robohash.org/estsintesse.png?size=200x200&set=set1', 'cmaclise27', 'rhXBhR');
insert into user (first, last, gender, avatar, username, password) values ('Eustacia', 'Olenchikov', 'Female', 'https://robohash.org/delectusodiominus.png?size=200x200&set=set1', 'eolenchikov28', 'PtzVYF5A');
insert into user (first, last, gender, avatar, username, password) values ('Bobby', 'Bolzen', 'Male', 'https://robohash.org/repellendusfacilisconsequatur.png?size=200x200&set=set1', 'bbolzen29', '9t0MaoSfP');
insert into user (first, last, gender, avatar, username, password) values ('Kelsey', 'Palia', 'Male', 'https://robohash.org/rerumetqui.png?size=200x200&set=set1', 'kpalia2a', 'tGHRth');
insert into user (first, last, gender, avatar, username, password) values ('Emmey', 'Sterrick', 'Female', 'https://robohash.org/nesciuntanimiasperiores.png?size=200x200&set=set1', 'esterrick2b', 'nZcZazPi');
insert into user (first, last, gender, avatar, username, password) values ('Charo', 'Kornilov', 'Female', 'https://robohash.org/evenietoccaecatisequi.png?size=200x200&set=set1', 'ckornilov2c', 'MFUR7qw');
insert into user (first, last, gender, avatar, username, password) values ('Rutter', 'Tinman', 'Male', 'https://robohash.org/sedconsequunturquisquam.png?size=200x200&set=set1', 'rtinman2d', '465BJef');
insert into user (first, last, gender, avatar, username, password) values ('Herby', 'Bleue', 'Male', 'https://robohash.org/quamutdolores.png?size=200x200&set=set1', 'hbleue2e', 'o6EdZa7dZ2X7');
insert into user (first, last, gender, avatar, username, password) values ('Rahel', 'Ricson', 'Female', 'https://robohash.org/veniametdolores.png?size=200x200&set=set1', 'rricson2f', 'G4KEQ8X');
insert into user (first, last, gender, avatar, username, password) values ('Tedra', 'Doveston', 'Female', 'https://robohash.org/facereetab.png?size=200x200&set=set1', 'tdoveston2g', 'ZYXR6XQhBq');
insert into user (first, last, gender, avatar, username, password) values ('Gauthier', 'Abram', 'Male', 'https://robohash.org/eumutofficiis.png?size=200x200&set=set1', 'gabram2h', '8lxfhIEnSHzZ');
insert into user (first, last, gender, avatar, username, password) values ('Greta', 'Chavrin', 'Female', 'https://robohash.org/eumdoloribusfugiat.png?size=200x200&set=set1', 'gchavrin2i', '0tXQQ4vu');
insert into user (first, last, gender, avatar, username, password) values ('Annora', 'Bellenger', 'Female', 'https://robohash.org/porrodistinctiovelit.png?size=200x200&set=set1', 'abellenger2j', 'WhVyITtWVRX2');
insert into user (first, last, gender, avatar, username, password) values ('Aloisia', 'Oram', 'Female', 'https://robohash.org/liberobeataemodi.png?size=200x200&set=set1', 'aoram2k', 'uPDfWuaj');
insert into user (first, last, gender, avatar, username, password) values ('Kristoffer', 'Blamphin', 'Male', 'https://robohash.org/estutsit.png?size=200x200&set=set1', 'kblamphin2l', '6XabhFbzd');
insert into user (first, last, gender, avatar, username, password) values ('Clara', 'Jaffra', 'Female', 'https://robohash.org/inventoredelenitiab.png?size=200x200&set=set1', 'cjaffra2m', '6CDTfcRbuwv');
insert into user (first, last, gender, avatar, username, password) values ('Morgan', 'Roblin', 'Male', 'https://robohash.org/voluptasoditcorporis.png?size=200x200&set=set1', 'mroblin2n', '370ri9bGKw');
insert into user (first, last, gender, avatar, username, password) values ('Bucky', 'Jesteco', 'Male', 'https://robohash.org/repudiandaeeummolestiae.png?size=200x200&set=set1', 'bjesteco2o', 'n7p1lmXxSI');
insert into user (first, last, gender, avatar, username, password) values ('Cornelius', 'Thoms', 'Male', 'https://robohash.org/nostrumetmolestiae.png?size=200x200&set=set1', 'cthoms2p', 'Cpnn3D4');
insert into user (first, last, gender, avatar, username, password) values ('Cristine', 'Worster', 'Female', 'https://robohash.org/quastemporibuset.png?size=200x200&set=set1', 'cworster2q', 'LPlw7LCtE');
insert into user (first, last, gender, avatar, username, password) values ('Mack', 'Scrimshire', 'Male', 'https://robohash.org/reiciendisutillum.png?size=200x200&set=set1', 'mscrimshire2r', 'Ac4hJO6ZGQ2');
